(function(g){var window=this;var Nta=function(a,b){return g.Vb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.I)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Zm(a.w,b,c)},Ota=function(a,b){var c=[];
g.fk(b,function(d){try{var e=g.ao.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.$n(e)&&c.push(d)},a);
return c},Pta=function(a,b){var c=Ota(a,b);
(0,g.y)(c,function(d){g.ao.prototype.remove.call(this,d)},a)},Qta=function(a,b){g.Za(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Rta=function(a,b){var c=b instanceof g.yc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},b6=function(){},Sta=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Tta=function(a){if(a.Bd&&"function"==typeof a.Bd)return a.Bd();
if("string"===typeof a)return a.split("");if(g.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Uta=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ja(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.se&&"function"==typeof a.se)var c=a.se();else if(a.Bd&&"function"==typeof a.Bd)c=void 0;else if(g.Ja(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Tta(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Vta=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Io[a]=!0;
var c=g.Go();c&&c.publish.apply(c,arguments);g.Io[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Wta(this,a.capabilities||""),Xta(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Wta=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Oa(Nta,Yta)).forEach(function(c){a.capabilities.add(c)})},Xta=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Zta=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},$ta=function(a){return new e6(a)},aua=function(a){return g.Ia(a)?(0,g.A)(a,$ta):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ia(a)?"["+(0,g.A)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},bua=function(a){return(0,g.A)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Va(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Va(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.is)(),c=(0,g.hs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},cua=function(){var a=(0,g.hs)();
a&&Pta(a,a.o.If(!0))},m6=function(){var a=g.ks("yt-remote-connected-devices")||[];
g.pb(a);return a},dua=function(a){if(g.$a(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.A)(a,function(d,e){return 0==e?d:d.substring(c.length)})},eua=function(a){g.js("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.ks("yt-remote-device-id");a||(a=i6(),g.js("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Za(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.Za(a,b);g.ls()&&g.rb(a,b);a=dua(a);if(g.$a(a))try{g.$q("remote_sid")}catch(c){}else try{g.Yq("remote_sid",a.join(","),-1)}catch(c){}},fua=function(){return g.ks("yt-remote-session-browser-channel")},gua=function(){return g.ks("yt-remote-local-screens")||[]},hua=function(){g.js("yt-remote-lounge-token-expiration",!0,86400)},iua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.A)(gua(),function(d){return d.loungeToken}),c=(0,g.A)(a,function(d){return d.loungeToken});
(0,g.pi)(c,function(d){return!g.Za(b,d)})&&hua();
g.js("yt-remote-local-screens",a,31536E3)},jua=function(a,b){g.js("yt-remote-session-browser-channel",a);
g.js("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.Za(c,d)||c.push(d);eua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.cb(a,o6());eua(a)},kua=function(){if(!r6){var a=g.mo();
a&&(r6=new g.Vn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},lua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},mua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?nua(a.shift(),function(){s6(a)}):t6()},oua=function(a){return"chrome-extension://"+a+"/cast_sender.js"},nua=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=mua();
a&&a(!1,"No cast extension found")},qua=function(){if(pua){var a=2,b=mua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;nua("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},rua=function(){qua();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(){},sua=function(){},uua=function(a){return(a=tua(a))?new ActiveXObject(a):new XMLHttpRequest},tua=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},v6=function(a,b,c){g.B.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.rd=b;this.u=(0,g.x)(this.XE,this);this.o=[]},w6=function(a){a.Da=g.yf(a.u,a.rd);
a.w.apply(null,a.o)},x6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.U1(this);this.u=new g.xf;this.u.setInterval(250)},wua=function(a,b,c){a.Ui=1;
a.xg=Z5(b.clone());a.ki=c;a.C=!0;vua(a,null)},y6=function(a,b,c,d,e){a.Ui=1;
a.xg=Z5(b.clone());a.ki=null;a.C=c;e&&(a.BB=!1);vua(a,d)},vua=function(a,b){a.Ej=(0,g.I)();
z6(a);a.hh=a.xg.clone();$5(a.hh,"t",a.F);a.fm=0;a.Jc=a.o.tq(a.o.Rl()?b:null);0<a.dr&&(a.Po=new v6((0,g.x)(a.BC,a,a.Jc),a.dr));a.A.ia(a.Jc,"readystatechange",a.bO);var c=a.Nh?g.ac(a.Nh):{};a.ki?(a.zp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Jc.send(a.hh,a.zp,a.ki,c)):(a.zp="GET",a.BB&&!g.Nd&&(c.Connection="close"),a.Jc.send(a.hh,a.zp,null,c));a.o.Te(1)},zua=function(a,b,c){for(var d=!0;!a.xh&&a.fm<c.length;){var e=xua(a,c);
if(e==A6){4==b&&(a.Jg=4,B6(15),d=!1);break}else if(e==yua){a.Jg=4;B6(16);d=!1;break}else C6(a,e)}4==b&&0==c.length&&(a.Jg=1,B6(17),d=!1);a.Ue=a.Ue&&d;d||(D6(a),E6(a))},xua=function(a,b){var c=a.fm,d=b.indexOf("\n",c);
if(-1==d)return A6;c=Number(b.substring(c,d));if(isNaN(c))return yua;d+=1;if(d+c>b.length)return A6;var e=b.substr(d,c);a.fm=d+c;return e},Bua=function(a,b){a.Ej=(0,g.I)();
z6(a);var c=b?window.location.hostname:"";a.hh=a.xg.clone();Y5(a.hh,"DOMAIN",c);Y5(a.hh,"t",a.F);try{a.Ye=new ActiveXObject("htmlfile")}catch(n){D6(a);a.Jg=7;B6(22);E6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in F6)k=F6[l];else if(l in Aua)k=F6[l]=Aua[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
F6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Uc(g.qc("b/12014412"),d+"</body></html>");a.Ye.open();a.Ye.write(g.Pc(c));a.Ye.close();a.Ye.parentWindow.m=(0,g.x)(a.tN,a);a.Ye.parentWindow.d=(0,g.x)(a.KA,a,!0);a.Ye.parentWindow.rpcClose=(0,g.x)(a.KA,a,!1);c=a.Ye.createElement("DIV");a.Ye.parentWindow.document.body.appendChild(c);d=g.Bc(a.hh.toString());d=g.ad(g.zc(d));d=g.Uc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Vc(c,d);a.o.Te(1)},z6=function(a){a.Au=(0,g.I)()+a.B;
Cua(a,a.B)},Cua=function(a,b){if(null!=a.Rj)throw Error("WatchDog timer not null");
a.Rj=G6((0,g.x)(a.BN,a),b)},H6=function(a){a.Rj&&(g.v.clearTimeout(a.Rj),a.Rj=null)},E6=function(a){a.o.rx()||a.xh||a.o.Ho(a)},D6=function(a){H6(a);
g.je(a.Po);a.Po=null;a.u.stop();g.Moa(a.A);if(a.Jc){var b=a.Jc;a.Jc=null;b.abort();b.dispose()}a.Ye&&(a.Ye=null)},C6=function(a,b){try{a.o.EA(a,b),a.o.Te(4)}catch(c){}},Eua=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Dua(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Eua(a,b,c,d,f)},f)})}},Dua=function(a,b,c){var d=new Image;
d.onload=function(){try{I6(d),c(!0)}catch(e){}};
d.onerror=function(){try{I6(d),c(!1)}catch(e){}};
d.onabort=function(){try{I6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{I6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Rta(d,a)},I6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},J6=function(){},Fua=function(a){this.o=a;
this.u=new J6},Gua=function(a){var b=K6(a.o,a.bk,"/mail/images/cleardot.gif");
Z5(b);Eua(b.toString(),5E3,(0,g.x)(a.UD,a),3,2E3);a.Te(1)},M6=function(a){var b=a.o.H;
if(null!=b)B6(5),b?(B6(11),L6(a.o,a,!1)):(B6(12),L6(a.o,a,!0));else if(a.Rd=new x6(a,void 0,void 0,void 0),a.Rd.Nh=a.Zq,b=a.o,b=K6(b,b.Rl()?a.Ak:null,a.ar),B6(5),!g.Ld||g.od(10))$5(b,"TYPE","xmlhttp"),y6(a.Rd,b,!1,a.Ak,!1);else{$5(b,"TYPE","html");var c=a.Rd;a=!!a.Ak;c.Ui=3;c.xg=Z5(b.clone());Bua(c,a)}},N6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Sta(a)},O6=function(a){g.Je.call(this);
this.headers=new g.Km;this.S=a||null;this.w=!1;this.O=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.Z=this.G=this.U=!1;this.F=0;this.J=null;this.ea="";this.P=this.V=!1},Hua=function(a){return g.Ld&&g.nd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Iua=function(a){return"content-type"==a.toLowerCase()},Kua=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;Jua(a);P6(a)},Jua=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Mua=function(a){if(a.w&&"undefined"!=typeof g.Z1)if(a.O[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.G&&4==Q6(a))g.yf(a.tx,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Lua.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<Q6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";Jua(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){Nua(a);
var c=a.o,d=a.O[0]?g.Fa:null;a.o=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Nua=function(a){a.o&&a.P&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},Q6=function(a){return a.o?a.o.readyState:0},S6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},T6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new J6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Oua=function(a,b){this.o=a;
this.map=b;this.context=null},Pua=function(a){g.le.call(this,"statevent",a)},Qua=function(a,b){g.le.call(this,"timingevent",a);
this.size=b},Rua=function(a){g.le.call(this,"serverreachability",a)},Uua=function(a){Sua(a);
if(3==a.o){var b=a.vl++,c=a.gn.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");U6(a,c);b=new x6(a,a.w,b,void 0);b.Ui=2;b.xg=Z5(c.clone());Rta(new Image,b.xg.toString());b.Ej=(0,g.I)();z6(b)}Tua(a)},Vua=function(a){a.qE(1,0);
a.gn=K6(a,null,a.Yq);V6(a)},Sua=function(a){a.Bg&&(a.Bg.abort(),a.Bg=null);
a.fc&&(a.fc.cancel(),a.fc=null);a.Kf&&(g.v.clearTimeout(a.Kf),a.Kf=null);W6(a);a.Kd&&(a.Kd.cancel(),a.Kd=null);a.Fg&&(g.v.clearTimeout(a.Fg),a.Fg=null)},Wua=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Oua(a.KJ++,b));2!=a.o&&3!=a.o||V6(a)},V6=function(a){a.Kd||a.Fg||(a.Fg=G6((0,g.x)(a.JA,a),0),a.Oi=0)},Yua=function(a,b){if(1==a.o){if(!b){a.vl=Math.floor(1E5*Math.random());
var c=a.vl++,d=new x6(a,"",c,void 0);d.Nh=null;var e=X6(a),f=a.gn.clone();Y5(f,"RID",c);Y5(f,"CVER","1");U6(a,f);wua(d,f,e);a.Kd=d;a.o=2}}else 3==a.o&&(b?Xua(a,b):0==a.u.length||a.Kd||Xua(a))},Xua=function(a,b){if(b)if(6<a.yh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.vl-1;var d=X6(a)}else c=b.G,d=b.ki;else c=a.vl++,d=X6(a);var e=a.gn.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.hj);U6(a,e);c=new x6(a,a.w,c,a.Oi+1);c.Nh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Kd=c;wua(c,e,d)},U6=function(a,b){if(a.od){var c=a.od.Ow();
c&&g.Lb(c,function(d,e){Y5(b,e,d)})}},X6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.yh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.yh?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Zua=function(a){a.fc||a.Kf||(a.F=1,a.Kf=G6((0,g.x)(a.IA,a),0),a.Hi=0)},Y6=function(a){if(a.fc||a.Kf||3<=a.Hi)return!1;
a.F++;a.Kf=G6((0,g.x)(a.IA,a),$ua(a,a.Hi));a.Hi++;return!0},L6=function(a,b,c){a.xp=c;
a.jf=b.Xf;a.C||Vua(a)},W6=function(a){null!=a.Ch&&(g.v.clearTimeout(a.Ch),a.Ch=null)},$ua=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.x)(a.MO,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),Z5(c));Dua(c.toString(),1E4,d)}else B6(2);ava(a,b)},ava=function(a,b){a.o=0;
a.od&&a.od.Zv(b);Tua(a);Sua(a)},Tua=function(a){a.o=0;
a.jf=-1;if(a.od)if(0==a.A.length&&0==a.u.length)a.od.jq();else{g.fb(a.A);var b=g.fb(a.u);a.A.length=0;a.u.length=0;a.od.jq(b)}},K6=function(a,b,c){var d=g.Vm(c);
if(""!=d.o)b&&g.Pm(d,b+"."+d.o),g.Qm(d,d.B);else{var e=window.location;d=Vta(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.nk&&g.Lb(a.nk,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.yh);U6(a,d);return d},G6=function(a,b){if(!g.Ka(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){$6.dispatchEvent(new Pua($6,a))},bva=function(){},a7=function(a,b,c){g.B.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.rd=b;this.B=(0,g.x)(this.WE,this);this.o=!1;this.u=0;this.w=this.Da=null;this.A=[]},cva=function(){this.o=[];
this.u=[]},dva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.o=new g.J(this.kN,0,this);g.H(this,this.o);this.rd=5E3;this.u=0;if(g.Ka(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ka(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Un;this.u=new b7(this.qO,this);this.o=null;this.vb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.P=c||!1},eva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.xp,sessionId:a.o.w,arrayId:a.o.hj}},fva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Yua(a.o),Uua(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},gva=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.bh(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.A,d,!0),onError:g.Oa(a.w,e),Nd:g.Oa(a.B,e)};c&&(a.zb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.sp(b,a)},kva=function(){var a=hva;
iva();h7.push(a);jva(h7)},i7=function(a,b){iva();
var c=h7,d=lva(a,String(b));g.$a(c)?mva(d):(jva(c),(0,g.y)(c,function(e){e(d)}))},iva=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",h7,void 0))},mva=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},jva=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},lva=function(a,b){var c=((0,g.I)()-nva)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},ova=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},pva=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Yd)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=ova(a,b[d])||c;return c},qva=function(a,b){var c=a.o.length;
a.o=(0,g.Yd)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Da=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},rva=function(a){if(a.o.length){var b=(0,g.A)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.hF,a),(0,g.x)(a.gF,a))}},o7=function(a){var b=aua(gua());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return pva(a,b)},q7=function(a,b){iua((0,g.A)(a.o,Zta));
b&&hua()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.ks("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Za(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Hk(this.o))},sva=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Hk(a.o)),a.o=b,a.R("screenChange"));tva(a)},u7=function(a){isNaN(a.w)||g.Fo(a.w);
a.w=g.Do((0,g.x)(a.Kt,a),0<a.A&&a.A<(0,g.I)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},uva=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Sb("Requesting availability of screen w/o lounge token.")});
return b},tva=function(a){a=g.Sb(g.Mb(a.o,function(b){return b}));
g.pb(a);a.length?g.js("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};vva(this)},xva=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ce();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);sva(a.u,l,function(m){e(m?l:null)})}else c?wva(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));sva(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},yva=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},wva=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={zb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.sp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},zva=function(a){a.o=a.w.ce();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},vva=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.pF,a));zva(a);a.A=aua(g.ks("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.ce,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.js("yt-remote-automatic-screen-cache",(0,g.A)(a.A,Zta)));x7(a);a.B[b.uuid]=b.id;g.js("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.ks("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.O=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.O,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.xP,this);this.B=(0,g.x)(this.JN,this);this.A=g.Do((0,g.x)(function(){Ava(this,null)},this),12E4)},Bva=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Fa,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Hk(b))},Ava=function(a,b){g.Fo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.Jo,a),d=(0,g.x)(a.he,a);a.ix(b,c,d,5)}}else a.he(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.S=c;this.B=null;this.F=g.Fa;this.C=NaN;this.P=(0,g.x)(this.AP,this);this.o=g.Fa},Cva=function(a){a.o=a.H.HC(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Fa;
this.Jo(b)},a),(0,g.x)(function(b){this.o=g.Fa;
this.he(b)},a))},Dva=function(a){var b={};
b.pairingCode=a.J;b.theme=a.S;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}kua()&&(b.env_useStageMdx=1);return g.$g(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Do((0,g.x)(this.ij,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.rM,this)},Eva=function(a,b){return b?g.Va(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},hva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.je(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.HA,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.ij(null)):a.R("yt-remote-cast2-session-change",null))},Fva=function(a){var b=a.u.GC(),c=a.o&&a.o.u;
a=(0,g.A)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Eva(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lva=function(a,b,c,d,e,f,k){Gva()?Hva(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Iva(a,c):(window.__onGCastApiAvailable=function(l,m){l?Iva(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Jva(),c(!1))},d?g.Po("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?rua():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(qua(),s6(Kva.map(oua))))):H7("Cannot initialize because not running Chrome")},Jva=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);Mva(!1);g.Lo(M7);M7.length=0},N7=function(){return!!g.ks("yt-remote-cast-installed")},Nva=function(){var a=g.ks("yt-remote-cast-receiver");
return a?a.friendlyName:null},Ova=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},Pva=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Ko("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Gva=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Cv||a},Qva=function(a,b){L7().init(a,b)},Hva=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.js("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.js("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.js("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Iva=function(a,b){K7(!0);
I7(!1);Qva(a,function(c){c?(Mva(!0),g.Mo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Jva());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.js("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Mva=function(a){H7("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.kf=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.kf=!1;a.hasNext=!1;a.F=0;a.C=(0,g.I)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.I)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.I)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.I)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.kf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new cva;this.w=this.u=null;this.H=(0,g.x)(this.sK,this);this.F=(0,g.x)(this.xl,this);this.G=(0,g.x)(this.rK,this);this.J=(0,g.x)(this.DK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Du,this),Rva(this))):c=3;0!=c&&(b?this.Du(c):g.Do((0,g.x)(function(){this.Du(c)},this),0));
var d=Pva();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},Rva=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Oa(this.oM,b),this))},a)},Sva=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){Sva(a);
a.A.setPlayerContextData(X7(b));Rva(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.xl(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.xl(a.w.media[0]))},Tva=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Sb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Sb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.P=!1;this.G=this.F=this.H=this.J=NaN;this.O=[];this.A=this.C=this.w=this.Sa=this.o=null;this.U=a;this.O.push(g.Bq(window,"beforeunload",(0,g.x)(this.ZE,this)));this.u=[];this.Sa=new R7;this.S=b.id;this.o=Uva(this,c);this.o.subscribe("handlerOpened",this.wK,this);this.o.subscribe("handlerClosed",this.tK,this);this.o.subscribe("handlerError",this.uK,this);this.o.subscribe("handlerMessage",this.vK,this);gva(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.ls()&&g.js("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Uva=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},Vva=function(a){a.B=g.Do((0,g.x)(function(){g8("Connecting timeout");
this.Mi(1)},a),2E4)},i8=function(a){g.Fo(a.B);
a.B=NaN},j8=function(a){g.Fo(a.J);
a.J=NaN},Wva=function(a){k8(a);
a.H=g.Do((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Fo(a.H);
a.H=NaN},Yva=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.gx()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),Xva(a)):a.Mi(1)},Zva=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.Yb(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.R("remotePlayerChange"))},$va=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.R("remoteQueueChange")},bwa=function(a,b){b.params=b.params||{};
$va(a,b);awa(a,b);a.R("autoplayDismissed")},awa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?Wva(a):k8(a);a.R("remotePlayerChange")},cwa=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.R("remotePlayerChange")}},dwa=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.R("remotePlayerChange")},ewa=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},fwa=function(a,b){var c="true"==b.params.hasNext;
a.Sa.kf="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.R("previousNextChange")},Xva=function(a){g.Fo(a.G);
a.G=g.Do((0,g.x)(a.Mi,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Hk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.qd=a;this.u=[];this.u.push(this.qd.$_s("screenChange",(0,g.x)(this.vP,this)));this.u.push(this.qd.$_s("onlineScreenChange",(0,g.x)(this.TL,this)))},kwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.M("MDX_CONFIG")||b;cua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),kua()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",o8,void 0));gwa();var c=p8();if(!c){var d=new v7(n8);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lva(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Hk(b)),s8.push(g.Ko("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.Ko("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Ko("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Ko("yt-remote-cast2-session-change",hwa)),s8.push(g.Ko("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Ova())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.To("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Hk(a)),iwa(a),c.start(),q8()||jwa())},mwa=function(){var a=lwa();
N7()&&g.ks("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},lwa=function(){var a=p8().qd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return bua(a)},y8=function(){var a=nwa();
!a&&N7()&&Nva()&&(a={key:"cast-selector-receiver",name:Nva()});return a},nwa=function(){var a=lwa(),b=w8();
b||(b=u8());return g.Va(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().ce();return k6(b,a)},hwa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},owa=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},pwa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||owa("");g.Ea("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.ls();
if(!a)return null;var b=p8().ce();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{owa(a.id);var c=new f8(n8,a,v8());c.connect(b,pwa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},jwa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),Ova(),r8("Skipping connecting because no session screen found."))},gwa=function(){var a=v8();
if(g.Yb(a)){a=o6();var b=g.ks("yt-remote-session-name")||"",c=g.ks("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},iwa=function(a){a?(g.js("yt-remote-session-app",a.app),g.js("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.B.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.H(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.pL);this.w.L(b,"captionschanged",this.qK);this.w.L(b,"captionssettingschanged",this.UB);this.w.L(b,"videoplayerreset",this.Ko);this.w.L(b,"mdxautoplaycancel",this.TD);this.S=this.w.L(b,"onVolumeChange",this.oA);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.DA,this);c.subscribe("remotePlayerChange",this.Bl,this);c.subscribe("remoteQueueChange",this.Ko,this);c.subscribe("autoplayUpNext",this.eA,
this);c.subscribe("previousNextChange",this.AA,this);c.subscribe("nowAutoplaying",this.wA,this);c.subscribe("autoplayDismissed",this.dA,this);this.suggestion=null;this.H=new g.lD(64);this.A=new g.J(this.SB,500,this);g.H(this,this.A);this.C=new g.J(this.TB,1E3,this);g.H(this,this.C);this.P=new a7(this.XO,0,this);g.H(this,this.P);this.F={};this.O=new g.J(this.uC,1E3,this);g.H(this,this.O);this.J=new v6(this.SH,1E3,this);g.H(this,this.J);this.U=g.Fa;this.UB();this.Ko();this.Bl()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.O=b||0;c.player.R("progresssync",b,d)},qwa=function(a){H8(a,0);
a.A.stop();I8(a,new g.lD(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.dc(c,b));a.o.HB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Xa;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.mf,g.uB(c));I8(a,new g.lD(1))},rwa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{qT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.rD(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.jT(a.u.app,d);a.H=b;swa(a.B,c,b)}},M8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.$L(this,250);g.H(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.bM()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.$L(this,250);g.H(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);twa(this,g.oL(a))},twa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.FM("Error on $RECEIVER_NAME",c):g.sD(b)||g.W(b,4)?g.FM("Playing on $RECEIVER_NAME",c):g.FM("Connected to $RECEIVER_NAME",c);a.ha("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.xO.call(this,"Play on",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.HP.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.S=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.lD(64);this.O=0;this.H=-1;this.C=null;if(!g.Fx(this.player.N())){a=this.player;var b=g.SC(a);b&&(b=b.ol())&&(b=new O8(a,b),g.H(this,b));b=new N8(a);g.H(this,b);g.GL(a,b.element,4);this.C=new M8;g.H(this,this.C);g.GL(a,this.C.element,4);this.P=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},swa=function(a,b,c){a.F=
c;
a.player.R("presentingplayerstatechange",new g.xD(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.P||!a.C);if(c?0:g.Ox(a.player.N())||"WEB_EMBEDDED_PLAYER"==a.player.N().deviceParams.c)g.sD(g.oL(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.ON,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.u.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2==a.player.app.U||1==a.player.app.U)&&g.R(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.mf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=g.uB(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Hk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().ce(),(c=k6(c,b.key))&&A8(c,1))}},Aua={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},F6={"'":"\\'"},uwa={},Yta={YP:"atp",DS:"ska",sS:"que",LR:"mus",CS:"sus",XQ:"dsp",zS:"seq"};
d6.prototype.Cg=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var r6,n6="",pua=lua("loadCastFramework")||lua("loadCastApplicationFramework"),Kva=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];u6.prototype.o=null;u6.prototype.getOptions=function(){var a;(a=this.o)||(a={},tua(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Qa(sua,u6);S8=new sua;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Qa(v6,g.B);g.h=v6.prototype;g.h.Ti=!1;g.h.zk=0;g.h.Da=null;g.h.qx=function(a){this.o=arguments;this.Da||this.zk?this.Ti=!0:w6(this)};
g.h.stop=function(){this.Da&&(g.v.clearTimeout(this.Da),this.Da=null,this.Ti=!1,this.o=[])};
g.h.pause=function(){this.zk++};
g.h.resume=function(){this.zk--;this.zk||!this.Ti||this.Da||(this.Ti=!1,w6(this))};
g.h.Y=function(){v6.Gb.Y.call(this);this.stop()};
g.h.XE=function(){this.Da=null;this.Ti&&!this.zk&&(this.Ti=!1,w6(this))};g.h=x6.prototype;g.h.Nh=null;g.h.Ue=!1;g.h.Rj=null;g.h.Au=null;g.h.Ej=null;g.h.Ui=null;g.h.xg=null;g.h.hh=null;g.h.ki=null;g.h.Jc=null;g.h.fm=0;g.h.Ye=null;g.h.zp=null;g.h.Jg=null;g.h.Bk=-1;g.h.BB=!0;g.h.xh=!1;g.h.dr=0;g.h.Po=null;var yua={},A6={};g.h=x6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.bO=function(a){a=a.target;var b=this.Po;b&&3==Q6(a)?b.qx():this.BC(a)};
g.h.BC=function(a){try{if(a==this.Jc)a:{var b=Q6(this.Jc),c=this.Jc.C,d=this.Jc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.th&&!S6(this.Jc))break a;this.xh||4!=b||7==c||(8==c||0>=d?this.o.Te(3):this.o.Te(2));H6(this);var e=this.Jc.getStatus();this.Bk=e;var f=S6(this.Jc);(this.Ue=200==e)?(4==b&&D6(this),this.C?(zua(this,b,f),g.th&&this.Ue&&3==b&&(this.A.ia(this.u,"tick",this.VN),this.u.start())):C6(this,f),this.Ue&&!this.xh&&(4==b?this.o.Ho(this):(this.Ue=
!1,z6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Jg=3,B6(13)):(this.Jg=0,B6(14)),D6(this),E6(this))}}catch(k){this.Jc&&S6(this.Jc)}finally{}};
g.h.VN=function(){var a=Q6(this.Jc),b=S6(this.Jc);this.fm<b.length&&(H6(this),zua(this,a,b),this.Ue&&4!=a&&z6(this))};
g.h.tN=function(a){G6((0,g.x)(this.sN,this,a),0)};
g.h.sN=function(a){this.xh||(H6(this),C6(this,a),z6(this))};
g.h.KA=function(a){G6((0,g.x)(this.rN,this,a),0)};
g.h.rN=function(a){this.xh||(D6(this),this.Ue=a,this.o.Ho(this),this.o.Te(4))};
g.h.cancel=function(){this.xh=!0;D6(this)};
g.h.BN=function(){this.Rj=null;var a=(0,g.I)();0<=a-this.Au?(2!=this.Ui&&this.o.Te(3),D6(this),this.Jg=2,B6(18),E6(this)):Cua(this,this.Au-a)};
g.h.getLastError=function(){return this.Jg};J6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=Fua.prototype;g.h.Zq=null;g.h.Rd=null;g.h.Qo=!1;g.h.sx=null;g.h.en=null;g.h.Kr=null;g.h.ar=null;g.h.xe=null;g.h.Xf=-1;g.h.Ak=null;g.h.bk=null;g.h.connect=function(a){this.ar=a;a=K6(this.o,null,this.ar);B6(3);this.sx=(0,g.I)();var b=this.o.G;null!=b?(this.Ak=b[0],(this.bk=b[1])?(this.xe=1,Gua(this)):(this.xe=2,M6(this))):($5(a,"MODE","init"),this.Rd=new x6(this,void 0,void 0,void 0),this.Rd.Nh=this.Zq,y6(this.Rd,a,!1,null,!0),this.xe=0)};
g.h.UD=function(a){if(a)this.xe=2,M6(this);else{B6(4);var b=this.o;b.jf=b.Bg.Xf;Z6(b,9)}a&&this.Te(2)};
g.h.tq=function(a){return this.o.tq(a)};
g.h.abort=function(){this.Rd&&(this.Rd.cancel(),this.Rd=null);this.Xf=-1};
g.h.rx=function(){return!1};
g.h.EA=function(a,b){this.Xf=a.Bk;if(0==this.xe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.jf=this.Xf;Z6(c,2);return}this.Ak=c[0];this.bk=c[1]}else c=this.o,c.jf=this.Xf,Z6(c,2);else if(2==this.xe)if(this.Qo)B6(7),this.Kr=(0,g.I)();else if("11111"==b){if(B6(6),this.Qo=!0,this.en=(0,g.I)(),c=this.en-this.sx,!g.Ld||g.od(10)||500>c)this.Xf=200,this.Rd.cancel(),B6(12),L6(this.o,this,!0)}else B6(8),this.en=this.Kr=(0,g.I)(),this.Qo=!1};
g.h.Ho=function(){this.Xf=this.Rd.Bk;if(this.Rd.Ue)0==this.xe?this.bk?(this.xe=1,Gua(this)):(this.xe=2,M6(this)):2==this.xe&&((!g.Ld||g.od(10)?!this.Qo:200>this.Kr-this.en)?(B6(11),L6(this.o,this,!1)):(B6(12),L6(this.o,this,!0)));else{0==this.xe?B6(9):2==this.xe&&B6(10);var a=this.o;this.Rd.getLastError();a.jf=this.Xf;Z6(a,2)}};
g.h.Rl=function(){return this.o.Rl()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Te=function(a){this.o.Te(a)};g.Qa(O6,g.Je);var Lua=/^https?$/i,vwa=["POST","PUT"];g.h=O6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.S?uua(this.S):uua(S8);this.O=this.S?this.S.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.tx,this);try{b6(R6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(R6(this,"Error opening Xhr: "+f.message));Kua(this,f);return}a=c||
"";var e=this.headers.clone();d&&Uta(d,function(f,k){e.set(k,f)});
d=g.Va(e.se(),Iua);c=g.v.FormData&&a instanceof g.v.FormData;!g.Za(vwa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{Nua(this),0<this.F&&(this.P=Hua(this.o),b6(R6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.P)),this.P?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.vx,this)):this.J=g.yf(this.vx,this.F,this)),b6(R6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(R6(this,"Send error: "+f.message)),Kua(this,f)}};
g.h.vx=function(){"undefined"!=typeof g.Z1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,R6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(R6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.Y=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),P6(this,!0));O6.Gb.Y.call(this)};
g.h.tx=function(){this.la()||(this.Z||this.G||this.B?Mua(this):this.qM())};
g.h.qM=function(){Mua(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<Q6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=T6.prototype;g.h.nk=null;g.h.Kd=null;g.h.fc=null;g.h.Yq=null;g.h.gn=null;g.h.Nv=null;g.h.yn=null;g.h.vl=0;g.h.KJ=0;g.h.od=null;g.h.Fg=null;g.h.Kf=null;g.h.Ch=null;g.h.Bg=null;g.h.xp=null;g.h.hj=-1;g.h.fy=-1;g.h.jf=-1;g.h.Oi=0;g.h.Hi=0;g.h.yh=8;var $6=new g.Je;g.Qa(Pua,g.le);g.Qa(Qua,g.le);g.Qa(Rua,g.le);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){B6(0);this.Yq=b;this.nk=c||{};d&&void 0!==e&&(this.nk.OSID=d,this.nk.OAID=e);this.C?(G6((0,g.x)(this.hw,this,a),100),Vua(this)):this.hw(a)};
g.h.hw=function(a){this.Bg=new Fua(this);this.Bg.Zq=null;this.Bg.u=this.B;this.Bg.connect(a)};
g.h.rx=function(){return 0==this.o};
g.h.JA=function(a){this.Fg=null;Yua(this,a)};
g.h.IA=function(){this.Kf=null;this.fc=new x6(this,this.w,"rpc",this.F);this.fc.Nh=null;this.fc.dr=0;var a=this.Nv.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.xp?"0":"1");Y5(a,"AID",this.hj);U6(this,a);if(!g.Ld||g.od(10))Y5(a,"TYPE","xmlhttp"),y6(this.fc,a,!0,this.yn,!1);else{Y5(a,"TYPE","html");var b=this.fc,c=!!this.yn;b.Ui=3;b.xg=Z5(a.clone());Bua(b,c)}};
g.h.EA=function(a,b){if(0!=this.o&&(this.fc==a||this.Kd==a))if(this.jf=a.Bk,this.Kd==a&&3==this.o)if(7<this.yh){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Kf){if(this.fc)if(this.fc.Ej+3E3<this.Kd.Ej)W6(this),this.fc.cancel(),this.fc=null;else break a;Y6(this);B6(19)}}else this.fy=c[1],0<this.fy-this.hj&&37500>c[2]&&this.xp&&0==this.Hi&&!this.Ch&&(this.Ch=G6((0,g.x)(this.mK,this),6E3));else Z6(this,11)}else b!=uwa.vQ.o&&Z6(this,11);else if(this.fc==
a&&W6(this),!g.wb(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.hj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.yn=e[2],e=e[3],null!=e?this.yh=e:this.yh=6,this.o=3,this.od&&this.od.cw(),this.Nv=K6(this,this.Rl()?this.yn:null,this.Yq),Zua(this)):"stop"==e[0]&&Z6(this,7):3==this.o&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.od&&this.od.bw(e),this.Hi=0)}}};
g.h.mK=function(){null!=this.Ch&&(this.Ch=null,this.fc.cancel(),this.fc=null,Y6(this),B6(20))};
g.h.Ho=function(a){if(this.fc==a){W6(this);this.fc=null;var b=2}else if(this.Kd==a)this.Kd=null,b=1;else return;this.jf=a.Bk;if(0!=this.o)if(a.Ue)1==b?(b=(0,g.I)()-a.Ej,$6.dispatchEvent(new Qua($6,a.ki?a.ki.length:0,b,this.Oi)),V6(this),this.A.length=0):Zua(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.jf)){if(d=1==b)this.Kd||this.Fg||1==this.o||2<=this.Oi?d=!1:(this.Fg=G6((0,g.x)(this.JA,this,a),$ua(this,this.Oi)),this.Oi++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,
5);break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.qE=function(a){if(!g.Za(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.MO=function(a){a?B6(2):(B6(1),ava(this,8))};
g.h.tq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.V=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.Te=function(a){$6.dispatchEvent(new Rua($6,a))};
g.h.Rl=function(){return!(!g.Ld||g.od(10))};
g.h=bva.prototype;g.h.cw=function(){};
g.h.bw=function(){};
g.h.Zv=function(){};
g.h.jq=function(){};
g.h.Ow=function(){return{}};
g.h.isActive=function(){return!0};g.Qa(a7,g.B);g.h=a7.prototype;g.h.VE=function(a){this.A=arguments;this.o=!1;this.Da?this.w=(0,g.I)()+this.rd:this.Da=g.yf(this.B,this.rd)};
g.h.stop=function(){this.Da&&(g.v.clearTimeout(this.Da),this.Da=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.Y=function(){this.stop();a7.Gb.Y.call(this)};
g.h.WE=function(){this.w?(this.Da=g.yf(this.B,this.w-(0,g.I)()),this.w=null):(this.Da=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.h=cva.prototype;g.h.isEmpty=function(){return g.$a(this.o)&&g.$a(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.Za(this.o,a)||g.Za(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Roa)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.u,a)};
g.h.Bd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(b7,g.B);g.h=b7.prototype;g.h.kN=function(){this.rd=Math.min(3E5,2*this.rd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.rd+15E3*Math.random();g.wn(this.o,a);this.u=(0,g.I)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.rd=5E3};g.Qa(c7,bva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.kg=function(a){return this.w.Oh(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.vb||(this.vb=!0,g.je(this.w),fva(this),g.je(this.u),this.u=null)};
g.h.la=function(){return this.vb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.o;e&&(e.od=null);d.od=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.hj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Wua(this.o,c)};
g.h.cw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Wua(this.o,a[b])}this.R("handlerOpened")};
g.h.Zv=function(a){var b=2==a&&401==this.o.jf;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.jq=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Ow=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.dc(a,this.B);return a};
g.h.bw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Uua(this.o)):this.R("handlerMessage",new dva(a[0],a[1]))};
g.h.qO=function(){this.u.isActive();var a=this.o,b=0;a.fc&&b++;a.Kd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var nva=(0,g.I)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Qa(m7,g.Q);m7.prototype.ce=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Da)&&this.FC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Da)||(g.Fo(this.Da),this.Da=NaN)};
g.h.Y=function(){this.stop();g.Q.prototype.Y.call(this)};
g.h.FC=function(){this.Da=NaN;this.o=g.sp(f7(this.C,"/pairing/get_screen"),{method:"POST",zb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.tP,this),onError:(0,g.x)(this.sP,this),Nd:(0,g.x)(this.uP,this)})};
g.h.tP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.R("pairingComplete",new e6(c))};
g.h.sP=function(a){this.o=null;a.status&&404==a.status?this.u>=wwa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=wwa[this.u],this.Da=g.Do((0,g.x)(this.FC,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.uP=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var wwa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.ks("yt-remote-lounge-token-expiration")&&rva(this);g.Fo(this.u);this.u=g.Do((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);ova(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||rva(this)};
g.h.remove=function(a,b){var c=o7(this);qva(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.tp=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.Y=function(){g.Fo(this.u);p7.Gb.Y.call(this)};
g.h.hF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.gF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.ks("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.I)()-144E5<a?0:a)?u7(this):(this.A=(0,g.I)()+3E5,g.js("yt-remote-fast-check-period",this.A),this.Kt())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.Y=function(){g.Fo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.Y.call(this)};
g.h.Kt=function(){g.Fo(this.w);this.w=NaN;this.u&&this.u.abort();var a=uva(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.OM,this,a),(0,g.x)(this.MM,this))}else t7(this,{}),u7(this)};
g.h.OM=function(a,b){this.u=null;var c=g.Sb(uva(this));if(g.qb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Sb("Changing Screen set during request."),this.Kt()};
g.h.MM=function(a){this.Sb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Sb=function(a){i7("OnlineScreenService",a)};g.Qa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.tp=function(a,b,c,d){this.w.contains(a)?this.w.tp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.ce=function(a){return a?this.o:g.eb(this.o,(0,g.Yd)(this.A,function(b){return!this.contains(b)},this))};
g.h.GC=function(){return(0,g.Yd)(this.ce(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.HC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.je(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.je(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.wP=function(a,b,c,d){g.sp(f7(this.C,"/pairing/get_screen"),{method:"POST",zb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||yva(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);yva(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.je(this.w);g.je(this.u);v7.Gb.Y.call(this)};
g.h.pF=function(){zva(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Qa(y7,g.Q);g.h=y7.prototype;g.h.Jo=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.he=function(a){this.la()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.O,a)};
g.h.JC=function(){return null};
g.h.Tt=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Tt("");y7.Gb.Y.call(this)};g.Qa(A7,y7);g.h=A7.prototype;g.h.St=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Bva(this)};
g.h.ij=function(a){this.info("launchWithParams no-op for Cast: "+g.Hk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.he()},this),(0,g.x)(function(){this.he(Error("Failed to stop receiver app."))},this)):this.he(Error("Stopping cast device witout session."))};
g.h.Tt=g.Fa;g.h.Y=function(){this.info("disposeInternal");g.Fo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Gb.Y.call(this)};
g.h.JN=function(a,b){if(!this.la())if(b){var c=N6(b);if(g.La(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hk(c));switch(d){case "mdxSessionStatus":Ava(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.ix=function(a,b,c,d){xva(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Do((0,g.x)(this.ix,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.JC=function(){return this.o};
g.h.xP=function(a){this.la()||a||(z7(this,"Cast session died."),this.he())};g.Qa(B7,y7);g.h=B7.prototype;g.h.St=function(a){this.A=a;this.A.addUpdateListener(this.P)};
g.h.ij=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Fa;g.Fo(this.C);this.A?this.A.stop((0,g.x)(this.he,this,null),(0,g.x)(this.he,this,"Failed to stop DIAL device.")):this.he()};
g.h.Y=function(){this.o();this.o=g.Fa;g.Fo(this.C);this.A&&this.A.removeUpdateListener(this.P);this.A=null;B7.Gb.Y.call(this)};
g.h.AP=function(a){this.la()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Fa,this.he())};
g.h.rr=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Dva(this));a(b);Cva(this)}else this.F=(0,g.x)(function(){g.Fo(this.C);this.F=g.Fa;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Dva(this));a(c);Cva(this)},this),this.C=g.Do((0,g.x)(function(){this.F()},this),100)};
g.h.JF=function(a,b,c){xva(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Jo(d),b(new chrome.cast.DialLaunchResponse(!1))):this.rr(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.rr(b,c)},this))};g.Qa(C7,y7);C7.prototype.stop=function(){this.he()};
C7.prototype.St=g.Fa;C7.prototype.ij=function(){g.Fo(this.o);this.o=NaN;var a=k6(this.H.ce(),this.u.label);a?this.Jo(a):this.he(Error("No such screen"))};
C7.prototype.Y=function(){g.Fo(this.o);this.o=NaN;C7.Gb.Y.call(this)};g.Qa(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.vM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.GA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.LK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.A),kva(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.IC,this)),this.w=Fva(this),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(k){this.Sb("Failed to set initial custom receivers: "+g.Hk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Sb("Failed to initialize API: "+g.Hk(k));
b(!1)},this))};
g.h.yO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.ce(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Eva(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Fa,(0,g.x)(function(e){this.Sb("Failed to set initial custom receivers: "+g.Hk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Tt(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.zO=function(a){this.la()?this.Sb("Setting connection data on disposed cast v2"):this.o?this.o.ij(a):this.Sb("Setting connection data without a session")};
g.h.zP=function(){this.la()?this.Sb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.GA,this),(0,g.x)(this.SM,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.IC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=hva,b=g.w("yt.mdx.remote.debug.handlers_");g.cb(b||[],a);g.je(this.o);D7.Gb.Y.call(this)};
g.h.Sb=function(a){i7("Controller",a)};
g.h.HA=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.rM=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Sb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Sb("Stopping receiver w/o session: "+a.friendlyName)}else this.Sb("onReceiverAction_ called without receiver.")};
g.h.LK=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Sb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Sb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Sb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.JF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.rr,b))};
g.h.GA=function(a){if(!this.la()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Sb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.ce(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.je(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.HA,this,this.o)),this.o.ij(null));this.o.St(a)}}};
g.h.yP=function(){return this.o?this.o.JC():null};
g.h.SM=function(a){this.la()||(this.Sb("Failed to estabilish a session: "+g.Hk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.vM=function(a){E7("Receiver availability updated: "+a);if(!this.la()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.IC=function(){this.la()||(this.w=Fva(this),E7("Updating custom receivers: "+g.Hk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(){this.Sb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.zO;D7.prototype.setConnectedScreenStatus=D7.prototype.yO;D7.prototype.stopSession=D7.prototype.zP;D7.prototype.getCastSession=D7.prototype.yP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.kf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Fa,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Fa,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Fa,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Oa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Fa,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Sb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Sb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Oa(this.setVolume,a,b))};
g.h.HB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Hk(b.style),g.dc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Oa(this.HB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Oa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Hk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.EC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Oa(this.EC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Oa(this.nextVideo,a,b))};
g.h.qw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.qw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.Y=function(){Sva(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.Y.call(this)};
g.h.Du=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.$a(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.oM=function(a,b){this.R(a,b)};
g.h.sK=function(a){if(!a)this.xl(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.xl=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Tva(this),this.R("remotePlayerChange")};
g.h.rK=function(a){a?(Tva(this),this.R("remotePlayerChange")):this.xl(null)};
g.h.DK=function(){var a=Pva();a&&Y7(this,a)};
g.h.Sb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Hk(l));this.o.connect({method:"setPlaylist",
params:g.Hk(l)},a,fua())}else g8("Connecting without params"),this.o.connect({},a,fua());Vva(this)};
g.h.dispose=function(){this.la()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.Y=function(){i8(this);k8(this);j8(this);g.Fo(this.F);this.F=NaN;g.Fo(this.G);this.G=NaN;this.w=null;g.Cq(this.O);this.O.length=0;this.o.dispose();g.Q.prototype.Y.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.ZE=function(){this.Mi(2)};
g.h.wK=function(){g8("Channel opened");this.P&&(this.P=!1,j8(this),this.J=g.Do((0,g.x)(function(){g8("Timing out waiting for a screen.");this.Mi(1)},this),15E3));
jua(eva(this.o),this.S)};
g.h.tK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.uK=function(a){q6();isNaN(this.uk())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.P=!0,g8("Channel error: "+a+" with reconnection in "+this.uk()+" ms"),h8(this,2))};
g.h.vK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Hk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=N6(a.params.devices);this.u=(0,g.A)(a,function(c){return new d6(c)});
a=!!g.Va(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Yva(this,a);break;case "loungeScreenDisconnected":g.db(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Yva(this,!1);break;case "remoteConnected":var b=new d6(N6(a.params.device));g.Va(this.u,function(c){return b?c.id==b.id:!1})||Qta(this.u,b);
break;case "remoteDisconnected":b=new d6(N6(a.params.device));g.db(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":$va(this,a);break;case "nowPlaying":bwa(this,a);break;case "onStateChange":awa(this,a);break;case "onAdStateChange":cwa(this,a);break;case "onVolumeChanged":dwa(this,a);break;case "onSubtitlesTrackChanged":Zva(this,a);break;case "nowAutoplaying":ewa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":fwa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.mO=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.OE=function(){var a=3;this.la()||(a=0,isNaN(this.uk())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Mi=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&q6();fva(this.o,a);this.dispose()};
g.h.NE=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.AO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.Fo(this.F),this.F=g.Do((0,g.x)(this.mO,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.Hk(this.Sa.o)==g.Hk(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.y)(c,function(d){this.R(d)},this)};
g.h.gx=function(){var a=this.o.C.id,b=g.Va(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.uk=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.I)():NaN};
g.h.CE=function(){return this.A||"UNSUPPORTED"};
g.h.DE=function(){return this.C||""};
g.h.rP=function(){if(!isNaN(this.uk())){var a=this.o.u;g.xn(a.o);a.start()}};
g.h.vO=function(a,b){l8(this,a,b);Xva(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.kg;f8.prototype.getProxyState=f8.prototype.OE;f8.prototype.disconnect=f8.prototype.Mi;f8.prototype.getPlayerContextData=f8.prototype.NE;f8.prototype.setPlayerContextData=f8.prototype.AO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.gx;f8.prototype.getReconnectTimeout=f8.prototype.uk;f8.prototype.getAutoplayMode=f8.prototype.CE;f8.prototype.getAutoplayVideoId=f8.prototype.DE;f8.prototype.reconnect=f8.prototype.rP;
f8.prototype.sendMessage=f8.prototype.vO;g.r(m8,m7);g.h=m8.prototype;g.h.ce=function(a){return this.qd.$_gs(a)};
g.h.contains=function(a){return!!this.qd.$_c(a)};
g.h.get=function(a){return this.qd.$_g(a)};
g.h.start=function(){this.qd.$_st()};
g.h.add=function(a,b,c){this.qd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.qd.$_r(a,b,c)};
g.h.tp=function(a,b,c,d){this.qd.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.u.length;a<b;++a)this.qd.$_ubk(this.u[a]);this.u.length=0;this.qd=null;m7.prototype.Y.call(this)};
g.h.vP=function(){this.R("screenChange")};
g.h.TL=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.wP;v7.prototype.$_gsppc=v7.prototype.HC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.tp;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.ce;v7.prototype.$_gos=v7.prototype.GC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.kg;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.B);g.h=G8.prototype;
g.h.Y=function(){g.B.prototype.Y.call(this);this.A.stop();this.C.stop();this.P.stop();this.U();this.o.unsubscribe("proxyStateChange",this.DA,this);this.o.unsubscribe("remotePlayerChange",this.Bl,this);this.o.unsubscribe("remoteQueueChange",this.Ko,this);this.o.unsubscribe("autoplayUpNext",this.eA,this);this.o.unsubscribe("previousNextChange",this.AA,this);this.o.unsubscribe("nowAutoplaying",this.wA,this);this.o.unsubscribe("autoplayDismissed",this.dA,this);this.o=this.B=null};
g.h.dz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.qx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.qK=function(a){this.P.VE(a)};
g.h.XO=function(a){this.dz("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.UB=function(){var a=this.u.getOption("captions","track");g.Yb(a)||K8(this,a)};
g.h.oA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.Bl,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.O.start();this.o.subscribe("remotePlayerChange",this.Bl,this)}};
g.h.pL=function(){g.Yb(this.F)||rwa(this,this.F);this.G=!1};
g.h.DA=function(a,b){this.C.stop();2==b&&this.TB()};
g.h.Bl=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.lD(8));this.SB();break;case 1085:case 3:I8(this,new g.lD(9));break;case 1083:case 0:I8(this,new g.lD(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.lD(4));break;case 2:I8(this,new g.lD(4));H8(this,V7(a));
break;case -1:I8(this,new g.lD(64));break;case -1E3:I8(this,new g.lD(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,rwa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.O.isActive()||this.uC()}else qwa(this)};
g.h.AA=function(){this.u.R("mdxpreviousnextchange")};
g.h.Ko=function(){J8(this)||qwa(this)};
g.h.TD=function(){this.o.qw()};
g.h.eA=function(){};
g.h.wA=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.dA=function(){this.u.R("mdxautoplaycanceled")};
g.h.SH=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.uC=function(){if(J8(this)){var a=$7(this.o);this.w.Wa(this.S);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.S=this.w.L(this.u,"onVolumeChange",this.oA)}};
g.h.SB=function(){this.A.stop();if(!this.o.la()){var a=$7(this.o);1==a.playerState&&I8(this,new g.lD(8));H8(this,V7(a));this.A.start()}};
g.h.TB=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.V);M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.V);N8.prototype.A=function(a){twa(this,a.state)};g.r(O8,g.xO);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.tb(a,this.B,this),g.zO(this,(0,g.A)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.Be(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.Re=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
O8.prototype.Zc=function(a){g.xO.prototype.Zc.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.gb()};g.r(P8,g.HP);g.h=P8.prototype;
g.h.create=function(){kwa(g.wx(this.player.N()));this.A.push(g.Ko("yt-remote-before-disconnect",this.nK,this));this.A.push(g.Ko("yt-remote-connection-change",this.wM,this));this.A.push(g.Ko("yt-remote-receiver-availability-change",this.BA,this));this.A.push(g.Ko("yt-remote-auto-connect",this.uM,this));this.A.push(g.Ko("yt-remote-receiver-resumed",this.tM,this));this.A.push(g.Ko("mdx-privacy-popup-confirm",this.YN,this));this.A.push(g.Ko("mdx-privacy-popup-cancel",this.XN,this));this.BA()};
g.h.load=function(){this.player.cancelPlayback();g.HP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=pwa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.O=a||0,this.player.R("progresssync",a,void 0));swa(this,this.F,this.F);g.pT(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.ke(this.B,this.o);this.o=this.B=null;g.HP.prototype.unload.call(this);g.pT(this.player.app,5);Q8(this)};
g.h.Y=function(){g.Lo(this.A);g.HP.prototype.Y.call(this)};
g.h.ll=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.dz.apply(this.B,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.H};
g.h.QE=function(){return this.loaded?this.B.suggestion:null};
g.h.kf=function(){return this.o?$7(this.o).kf:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.O};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Pc():!a.isAdPlaying()&&this.player.Pc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.yH=function(){this.o&&this.o.EC()};
g.h.nK=function(a){1==a&&(this.S=this.o?$7(this.o):null)};
g.h.wM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.S=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.je(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.S)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.BA=function(){this.J=[this.u].concat(mwa());var a=y8()||this.u;R8(this,a);this.player.ka("onMdxReceiversChange")};
g.h.ON=function(a){!this.P&&g.zD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.uM=function(){var a=y8();R8(this,a)};
g.h.tM=function(){this.w=y8()};
g.h.YN=function(){this.P=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.XN=function(){this.P=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Mc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.zH=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Af=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WP.remote=P8;})(_yt_player);
